// This file is generated by zbuild. Do not edit manually.

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const dep_snappy = b.dependency("snappy", .{});

    const dep_yaml = b.dependency("yaml", .{});

    const dep_hashtree = b.dependency("hashtree", .{});

    const dep_zbench = b.dependency("zbench", .{});

    const write_files_codegen = b.addWriteFiles();

    const options_build_options = b.addOptions();
    const option_zero_hash_max_depth = b.option(u8, "zero_hash_max_depth", "");
    options_build_options.addOption(?u8, "zero_hash_max_depth", option_zero_hash_max_depth);
    const option_preset = b.option([]const u8, "preset", "") orelse "mainnet";
    options_build_options.addOption([]const u8, "preset", option_preset);
    const options_module_build_options = options_build_options.createModule();

    const options_spec_test_options = b.addOptions();
    const option_spec_test_url = b.option([]const u8, "spec_test_url", "") orelse "https://github.com/ethereum/consensus-spec-tests";
    options_spec_test_options.addOption([]const u8, "spec_test_url", option_spec_test_url);
    const option_spec_test_version = b.option([]const u8, "spec_test_version", "") orelse "v1.5.0-beta.2";
    options_spec_test_options.addOption([]const u8, "spec_test_version", option_spec_test_version);
    const option_spec_test_out_dir = b.option([]const u8, "spec_test_out_dir", "") orelse "test/spec/spec_tests";
    options_spec_test_options.addOption([]const u8, "spec_test_out_dir", option_spec_test_out_dir);
    const options_module_spec_test_options = options_spec_test_options.createModule();

    const module_hex = b.createModule(.{
        .root_source_file = b.path("src/hex.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("hex"), module_hex) catch @panic("OOM");

    const module_hashing = b.createModule(.{
        .root_source_file = b.path("src/hashing/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("hashing"), module_hashing) catch @panic("OOM");

    const module_persistent_merkle_tree = b.createModule(.{
        .root_source_file = b.path("src/persistent_merkle_tree/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("persistent_merkle_tree"), module_persistent_merkle_tree) catch @panic("OOM");

    const module_ssz = b.createModule(.{
        .root_source_file = b.path("src/ssz/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("ssz"), module_ssz) catch @panic("OOM");

    const module_consensus_types = b.createModule(.{
        .root_source_file = b.path("src/consensus_types/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("consensus_types"), module_consensus_types) catch @panic("OOM");

    const module_types_codegen = b.createModule(.{
        .root_source_file = b.path("test/lodestar_types/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("types_codegen"), module_types_codegen) catch @panic("OOM");

    const exe_types_codegen = b.addExecutable(.{
        .name = "types_codegen",
        .root_module = module_types_codegen,
    });

    const install_exe_types_codegen = b.addInstallArtifact(exe_types_codegen, .{});
    const tls_install_exe_types_codegen = b.step("build-exe:types_codegen", "Install the types_codegen executable");
    tls_install_exe_types_codegen.dependOn(&install_exe_types_codegen.step);
    b.getInstallStep().dependOn(&install_exe_types_codegen.step);

    const run_exe_types_codegen = b.addRunArtifact(exe_types_codegen);
    if (b.args) |args| run_exe_types_codegen.addArgs(args);
    const tls_run_exe_types_codegen = b.step("run:types_codegen", "Run the types_codegen executable");
    tls_run_exe_types_codegen.dependOn(&run_exe_types_codegen.step);

    const module_download_spec_tests = b.createModule(.{
        .root_source_file = b.path("test/spec/download_spec_tests.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("download_spec_tests"), module_download_spec_tests) catch @panic("OOM");

    const exe_download_spec_tests = b.addExecutable(.{
        .name = "download_spec_tests",
        .root_module = module_download_spec_tests,
    });

    const install_exe_download_spec_tests = b.addInstallArtifact(exe_download_spec_tests, .{});
    const tls_install_exe_download_spec_tests = b.step("build-exe:download_spec_tests", "Install the download_spec_tests executable");
    tls_install_exe_download_spec_tests.dependOn(&install_exe_download_spec_tests.step);
    b.getInstallStep().dependOn(&install_exe_download_spec_tests.step);

    const run_exe_download_spec_tests = b.addRunArtifact(exe_download_spec_tests);
    if (b.args) |args| run_exe_download_spec_tests.addArgs(args);
    const tls_run_exe_download_spec_tests = b.step("run:download_spec_tests", "Run the download_spec_tests executable");
    tls_run_exe_download_spec_tests.dependOn(&run_exe_download_spec_tests.step);

    const module_write_generic_spec_tests = b.createModule(.{
        .root_source_file = b.path("test/spec/write_generic_tests.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("write_generic_spec_tests"), module_write_generic_spec_tests) catch @panic("OOM");

    const exe_write_generic_spec_tests = b.addExecutable(.{
        .name = "write_generic_spec_tests",
        .root_module = module_write_generic_spec_tests,
    });

    const install_exe_write_generic_spec_tests = b.addInstallArtifact(exe_write_generic_spec_tests, .{});
    const tls_install_exe_write_generic_spec_tests = b.step("build-exe:write_generic_spec_tests", "Install the write_generic_spec_tests executable");
    tls_install_exe_write_generic_spec_tests.dependOn(&install_exe_write_generic_spec_tests.step);
    b.getInstallStep().dependOn(&install_exe_write_generic_spec_tests.step);

    const run_exe_write_generic_spec_tests = b.addRunArtifact(exe_write_generic_spec_tests);
    if (b.args) |args| run_exe_write_generic_spec_tests.addArgs(args);
    const tls_run_exe_write_generic_spec_tests = b.step("run:write_generic_spec_tests", "Run the write_generic_spec_tests executable");
    tls_run_exe_write_generic_spec_tests.dependOn(&run_exe_write_generic_spec_tests.step);

    const module_write_static_spec_tests = b.createModule(.{
        .root_source_file = b.path("test/spec/write_static_tests.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("write_static_spec_tests"), module_write_static_spec_tests) catch @panic("OOM");

    const exe_write_static_spec_tests = b.addExecutable(.{
        .name = "write_static_spec_tests",
        .root_module = module_write_static_spec_tests,
    });

    const install_exe_write_static_spec_tests = b.addInstallArtifact(exe_write_static_spec_tests, .{});
    const tls_install_exe_write_static_spec_tests = b.step("build-exe:write_static_spec_tests", "Install the write_static_spec_tests executable");
    tls_install_exe_write_static_spec_tests.dependOn(&install_exe_write_static_spec_tests.step);
    b.getInstallStep().dependOn(&install_exe_write_static_spec_tests.step);

    const run_exe_write_static_spec_tests = b.addRunArtifact(exe_write_static_spec_tests);
    if (b.args) |args| run_exe_write_static_spec_tests.addArgs(args);
    const tls_run_exe_write_static_spec_tests = b.step("run:write_static_spec_tests", "Run the write_static_spec_tests executable");
    tls_run_exe_write_static_spec_tests.dependOn(&run_exe_write_static_spec_tests.step);

    const module_bench_state = b.createModule(.{
        .root_source_file = b.path("bench/state.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("bench_state"), module_bench_state) catch @panic("OOM");

    const exe_bench_state = b.addExecutable(.{
        .name = "bench_state",
        .root_module = module_bench_state,
    });

    const install_exe_bench_state = b.addInstallArtifact(exe_bench_state, .{});
    const tls_install_exe_bench_state = b.step("build-exe:bench_state", "Install the bench_state executable");
    tls_install_exe_bench_state.dependOn(&install_exe_bench_state.step);
    b.getInstallStep().dependOn(&install_exe_bench_state.step);

    const run_exe_bench_state = b.addRunArtifact(exe_bench_state);
    if (b.args) |args| run_exe_bench_state.addArgs(args);
    const tls_run_exe_bench_state = b.step("run:bench_state", "Run the bench_state executable");
    tls_run_exe_bench_state.dependOn(&run_exe_bench_state.step);

    const module_types = b.createModule(.{
        .root_source_file = write_files_codegen.getDirectory().path(b, "types"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("types"), module_types) catch @panic("OOM");

    const lib_types = b.addLibrary(.{
        .name = "types",
        .root_module = module_types,
    });

    const install_lib_types = b.addInstallArtifact(lib_types, .{});
    const tls_install_lib_types = b.step("build-lib:types", "Install the types library");
    tls_install_lib_types.dependOn(&install_lib_types.step);
    b.getInstallStep().dependOn(&install_lib_types.step);

    const tls_run_test = b.step("test", "Run all tests");

    const test_hex = b.addTest(.{
        .name = "hex",
        .root_module = module_hex,
        .filters = &[_][]const u8{  },
    });
    const install_test_hex = b.addInstallArtifact(test_hex, .{});
    const tls_install_test_hex = b.step("build-test:hex", "Install the hex test");
    tls_install_test_hex.dependOn(&install_test_hex.step);

    const run_test_hex = b.addRunArtifact(test_hex);
    const tls_run_test_hex = b.step("test:hex", "Run the hex test");
    tls_run_test_hex.dependOn(&run_test_hex.step);
    tls_run_test.dependOn(&run_test_hex.step);

    const test_hashing = b.addTest(.{
        .name = "hashing",
        .root_module = module_hashing,
        .filters = &[_][]const u8{  },
    });
    const install_test_hashing = b.addInstallArtifact(test_hashing, .{});
    const tls_install_test_hashing = b.step("build-test:hashing", "Install the hashing test");
    tls_install_test_hashing.dependOn(&install_test_hashing.step);

    const run_test_hashing = b.addRunArtifact(test_hashing);
    const tls_run_test_hashing = b.step("test:hashing", "Run the hashing test");
    tls_run_test_hashing.dependOn(&run_test_hashing.step);
    tls_run_test.dependOn(&run_test_hashing.step);

    const test_persistent_merkle_tree = b.addTest(.{
        .name = "persistent_merkle_tree",
        .root_module = module_persistent_merkle_tree,
        .filters = &[_][]const u8{  },
    });
    const install_test_persistent_merkle_tree = b.addInstallArtifact(test_persistent_merkle_tree, .{});
    const tls_install_test_persistent_merkle_tree = b.step("build-test:persistent_merkle_tree", "Install the persistent_merkle_tree test");
    tls_install_test_persistent_merkle_tree.dependOn(&install_test_persistent_merkle_tree.step);

    const run_test_persistent_merkle_tree = b.addRunArtifact(test_persistent_merkle_tree);
    const tls_run_test_persistent_merkle_tree = b.step("test:persistent_merkle_tree", "Run the persistent_merkle_tree test");
    tls_run_test_persistent_merkle_tree.dependOn(&run_test_persistent_merkle_tree.step);
    tls_run_test.dependOn(&run_test_persistent_merkle_tree.step);

    const test_ssz = b.addTest(.{
        .name = "ssz",
        .root_module = module_ssz,
        .filters = &[_][]const u8{  },
    });
    const install_test_ssz = b.addInstallArtifact(test_ssz, .{});
    const tls_install_test_ssz = b.step("build-test:ssz", "Install the ssz test");
    tls_install_test_ssz.dependOn(&install_test_ssz.step);

    const run_test_ssz = b.addRunArtifact(test_ssz);
    const tls_run_test_ssz = b.step("test:ssz", "Run the ssz test");
    tls_run_test_ssz.dependOn(&run_test_ssz.step);
    tls_run_test.dependOn(&run_test_ssz.step);

    const test_consensus_types = b.addTest(.{
        .name = "consensus_types",
        .root_module = module_consensus_types,
        .filters = &[_][]const u8{  },
    });
    const install_test_consensus_types = b.addInstallArtifact(test_consensus_types, .{});
    const tls_install_test_consensus_types = b.step("build-test:consensus_types", "Install the consensus_types test");
    tls_install_test_consensus_types.dependOn(&install_test_consensus_types.step);

    const run_test_consensus_types = b.addRunArtifact(test_consensus_types);
    const tls_run_test_consensus_types = b.step("test:consensus_types", "Run the consensus_types test");
    tls_run_test_consensus_types.dependOn(&run_test_consensus_types.step);
    tls_run_test.dependOn(&run_test_consensus_types.step);

    const test_types_codegen = b.addTest(.{
        .name = "types_codegen",
        .root_module = module_types_codegen,
        .filters = &[_][]const u8{  },
    });
    const install_test_types_codegen = b.addInstallArtifact(test_types_codegen, .{});
    const tls_install_test_types_codegen = b.step("build-test:types_codegen", "Install the types_codegen test");
    tls_install_test_types_codegen.dependOn(&install_test_types_codegen.step);

    const run_test_types_codegen = b.addRunArtifact(test_types_codegen);
    const tls_run_test_types_codegen = b.step("test:types_codegen", "Run the types_codegen test");
    tls_run_test_types_codegen.dependOn(&run_test_types_codegen.step);
    tls_run_test.dependOn(&run_test_types_codegen.step);

    const test_download_spec_tests = b.addTest(.{
        .name = "download_spec_tests",
        .root_module = module_download_spec_tests,
        .filters = &[_][]const u8{  },
    });
    const install_test_download_spec_tests = b.addInstallArtifact(test_download_spec_tests, .{});
    const tls_install_test_download_spec_tests = b.step("build-test:download_spec_tests", "Install the download_spec_tests test");
    tls_install_test_download_spec_tests.dependOn(&install_test_download_spec_tests.step);

    const run_test_download_spec_tests = b.addRunArtifact(test_download_spec_tests);
    const tls_run_test_download_spec_tests = b.step("test:download_spec_tests", "Run the download_spec_tests test");
    tls_run_test_download_spec_tests.dependOn(&run_test_download_spec_tests.step);
    tls_run_test.dependOn(&run_test_download_spec_tests.step);

    const test_write_generic_spec_tests = b.addTest(.{
        .name = "write_generic_spec_tests",
        .root_module = module_write_generic_spec_tests,
        .filters = &[_][]const u8{  },
    });
    const install_test_write_generic_spec_tests = b.addInstallArtifact(test_write_generic_spec_tests, .{});
    const tls_install_test_write_generic_spec_tests = b.step("build-test:write_generic_spec_tests", "Install the write_generic_spec_tests test");
    tls_install_test_write_generic_spec_tests.dependOn(&install_test_write_generic_spec_tests.step);

    const run_test_write_generic_spec_tests = b.addRunArtifact(test_write_generic_spec_tests);
    const tls_run_test_write_generic_spec_tests = b.step("test:write_generic_spec_tests", "Run the write_generic_spec_tests test");
    tls_run_test_write_generic_spec_tests.dependOn(&run_test_write_generic_spec_tests.step);
    tls_run_test.dependOn(&run_test_write_generic_spec_tests.step);

    const test_write_static_spec_tests = b.addTest(.{
        .name = "write_static_spec_tests",
        .root_module = module_write_static_spec_tests,
        .filters = &[_][]const u8{  },
    });
    const install_test_write_static_spec_tests = b.addInstallArtifact(test_write_static_spec_tests, .{});
    const tls_install_test_write_static_spec_tests = b.step("build-test:write_static_spec_tests", "Install the write_static_spec_tests test");
    tls_install_test_write_static_spec_tests.dependOn(&install_test_write_static_spec_tests.step);

    const run_test_write_static_spec_tests = b.addRunArtifact(test_write_static_spec_tests);
    const tls_run_test_write_static_spec_tests = b.step("test:write_static_spec_tests", "Run the write_static_spec_tests test");
    tls_run_test_write_static_spec_tests.dependOn(&run_test_write_static_spec_tests.step);
    tls_run_test.dependOn(&run_test_write_static_spec_tests.step);

    const test_bench_state = b.addTest(.{
        .name = "bench_state",
        .root_module = module_bench_state,
        .filters = &[_][]const u8{  },
    });
    const install_test_bench_state = b.addInstallArtifact(test_bench_state, .{});
    const tls_install_test_bench_state = b.step("build-test:bench_state", "Install the bench_state test");
    tls_install_test_bench_state.dependOn(&install_test_bench_state.step);

    const run_test_bench_state = b.addRunArtifact(test_bench_state);
    const tls_run_test_bench_state = b.step("test:bench_state", "Run the bench_state test");
    tls_run_test_bench_state.dependOn(&run_test_bench_state.step);
    tls_run_test.dependOn(&run_test_bench_state.step);

    const test_types = b.addTest(.{
        .name = "types",
        .root_module = module_types,
        .filters = &[_][]const u8{  },
    });
    const install_test_types = b.addInstallArtifact(test_types, .{});
    const tls_install_test_types = b.step("build-test:types", "Install the types test");
    tls_install_test_types.dependOn(&install_test_types.step);

    const run_test_types = b.addRunArtifact(test_types);
    const tls_run_test_types = b.step("test:types", "Run the types test");
    tls_run_test_types.dependOn(&run_test_types.step);
    tls_run_test.dependOn(&run_test_types.step);

    const module_int = b.createModule(.{
        .root_source_file = b.path("test/int/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("int"), module_int) catch @panic("OOM");

    const test_int = b.addTest(.{
        .name = "int",
        .root_module = module_int,
        .filters = &[_][]const u8{  },
    });
    const install_test_int = b.addInstallArtifact(test_int, .{});
    const tls_install_test_int = b.step("build-test:int", "Install the int test");
    tls_install_test_int.dependOn(&install_test_int.step);

    const run_test_int = b.addRunArtifact(test_int);
    const tls_run_test_int = b.step("test:int", "Run the int test");
    tls_run_test_int.dependOn(&run_test_int.step);
    tls_run_test.dependOn(&run_test_int.step);

    const module_generic_spec_tests = b.createModule(.{
        .root_source_file = b.path("test/spec/generic_tests.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("generic_spec_tests"), module_generic_spec_tests) catch @panic("OOM");

    const test_generic_spec_tests = b.addTest(.{
        .name = "generic_spec_tests",
        .root_module = module_generic_spec_tests,
        .filters = &[_][]const u8{  },
    });
    const install_test_generic_spec_tests = b.addInstallArtifact(test_generic_spec_tests, .{});
    const tls_install_test_generic_spec_tests = b.step("build-test:generic_spec_tests", "Install the generic_spec_tests test");
    tls_install_test_generic_spec_tests.dependOn(&install_test_generic_spec_tests.step);

    const run_test_generic_spec_tests = b.addRunArtifact(test_generic_spec_tests);
    const tls_run_test_generic_spec_tests = b.step("test:generic_spec_tests", "Run the generic_spec_tests test");
    tls_run_test_generic_spec_tests.dependOn(&run_test_generic_spec_tests.step);
    tls_run_test.dependOn(&run_test_generic_spec_tests.step);

    const module_static_spec_tests = b.createModule(.{
        .root_source_file = b.path("test/spec/static_tests.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("static_spec_tests"), module_static_spec_tests) catch @panic("OOM");

    const test_static_spec_tests = b.addTest(.{
        .name = "static_spec_tests",
        .root_module = module_static_spec_tests,
        .filters = &[_][]const u8{  },
    });
    const install_test_static_spec_tests = b.addInstallArtifact(test_static_spec_tests, .{});
    const tls_install_test_static_spec_tests = b.step("build-test:static_spec_tests", "Install the static_spec_tests test");
    tls_install_test_static_spec_tests.dependOn(&install_test_static_spec_tests.step);

    const run_test_static_spec_tests = b.addRunArtifact(test_static_spec_tests);
    const tls_run_test_static_spec_tests = b.step("test:static_spec_tests", "Run the static_spec_tests test");
    tls_run_test_static_spec_tests.dependOn(&run_test_static_spec_tests.step);
    tls_run_test.dependOn(&run_test_static_spec_tests.step);

    _ = write_files_codegen.addCopyFile(run_exe_types_codegen.captureStdOut(), "types");

    module_hashing.addImport("build_options", options_module_build_options);
    module_hashing.addImport("hex", module_hex);
    module_hashing.addImport("hashtree", dep_hashtree.module("hashtree"));

    module_persistent_merkle_tree.addImport("build_options", options_module_build_options);
    module_persistent_merkle_tree.addImport("hex", module_hex);
    module_persistent_merkle_tree.addImport("hashing", module_hashing);

    module_ssz.addImport("build_options", options_module_build_options);
    module_ssz.addImport("hex", module_hex);
    module_ssz.addImport("hashing", module_hashing);

    module_consensus_types.addImport("build_options", options_module_build_options);
    module_consensus_types.addImport("ssz", module_ssz);

    module_types_codegen.addImport("ssz", module_ssz);

    module_download_spec_tests.addImport("spec_test_options", options_module_spec_test_options);

    module_write_generic_spec_tests.addImport("spec_test_options", options_module_spec_test_options);

    module_write_static_spec_tests.addImport("spec_test_options", options_module_spec_test_options);

    module_bench_state.addImport("consensus_types", module_consensus_types);
    module_bench_state.addImport("ssz", module_ssz);
    module_bench_state.addImport("zbench", dep_zbench.module("zbench"));

    module_int.addImport("hex", module_hex);
    module_int.addImport("ssz", module_ssz);

    module_generic_spec_tests.addImport("hex", module_hex);
    module_generic_spec_tests.addImport("snappy", dep_snappy.module("snappy"));
    module_generic_spec_tests.addImport("ssz", module_ssz);
    module_generic_spec_tests.addImport("spec_test_options", options_module_spec_test_options);
    module_generic_spec_tests.addImport("yaml", dep_yaml.module("yaml"));

    module_static_spec_tests.addImport("hex", module_hex);
    module_static_spec_tests.addImport("snappy", dep_snappy.module("snappy"));
    module_static_spec_tests.addImport("ssz", module_ssz);
    module_static_spec_tests.addImport("build_options", options_module_build_options);
    module_static_spec_tests.addImport("spec_test_options", options_module_spec_test_options);
    module_static_spec_tests.addImport("consensus_types", module_consensus_types);
    module_static_spec_tests.addImport("yaml", dep_yaml.module("yaml"));

}
